# ============================================================================
# ExternalSecret - GCP Secret Manager
# ============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  namespace: petclinic
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secrets-manager
    kind: ClusterSecretStore
  target:
    name: petclinic-db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: petclinic-dr-db-credentials
        property: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: petclinic-dr-db-credentials
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: petclinic-dr-db-credentials
        property: SPRING_DATASOURCE_PASSWORD
