# ============================================================================
# Service Patches - GCE Ingress용 NodePort + BackendConfig + Standalone NEG
# ============================================================================
# Standalone NEG: 클러스터 재생성 시에도 NEG 이름 유지 + 엔드포인트 자동 등록
# ============================================================================
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-backend-config"}'
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "petclinic-api-gateway-neg"}}}'
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "admin-server-backend-config"}'
    cloud.google.com/neg: '{"exposed_ports": {"9090":{"name": "petclinic-admin-server-neg"}}}'
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "grafana-backend-config"}'
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "prometheus-backend-config"}'
spec:
  type: NodePort
