# ============================================================================
# Service Patches - BackendConfig 연결
# ============================================================================
apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "grafana-backend-config"}'
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "prometheus-backend-config"}'
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-backend-config"}'
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "petclinic-api-gateway-neg"}}}'
