# ============================================================================
# Service Patches - GCE Ingress용 NodePort + BackendConfig + NEG 연결
# ============================================================================
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "admin-server-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "grafana-backend-config"}'
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: petclinic
  annotations:
    cloud.google.com/backend-config: '{"default": "prometheus-backend-config"}'
spec:
  type: NodePort
